import os

RAGATOUILLE_PATH = os.environ.get('RAGATOUILLE_PATH', '.ragatouille/colbert/indexes')
COLBERTRAG_CHUNK_SIZE = 256
COLBERTRAG_MAX_WORKERS = 10
COLBERTRAG_GRPC_PORT = 50051
COLBERTRAG_FASTAPI_PORT = 8000
COLBERTRAG_HOST = '0.0.0.0'
