# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: colbertrag.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63olbertrag.proto\x12\ncolbertrag\"#\n\x07Request\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\"\x87\x01\n\x08\x44ocument\x12\x14\n\x0cpage_content\x18\x01 \x01(\t\x12\x34\n\x08metadata\x18\x02 \x03(\x0b\x32\".colbertrag.Document.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"3\n\x08Response\x12\'\n\tdocuments\x18\x01 \x03(\x0b\x32\x14.colbertrag.Document2C\n\nColbertRAG\x12\x35\n\x08Retrieve\x12\x13.colbertrag.Request\x1a\x14.colbertrag.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'colbertrag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._loaded_options = None
  _globals['_DOCUMENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_REQUEST']._serialized_start=32
  _globals['_REQUEST']._serialized_end=67
  _globals['_DOCUMENT']._serialized_start=70
  _globals['_DOCUMENT']._serialized_end=205
  _globals['_DOCUMENT_METADATAENTRY']._serialized_start=158
  _globals['_DOCUMENT_METADATAENTRY']._serialized_end=205
  _globals['_RESPONSE']._serialized_start=207
  _globals['_RESPONSE']._serialized_end=258
  _globals['_COLBERTRAG']._serialized_start=260
  _globals['_COLBERTRAG']._serialized_end=327
# @@protoc_insertion_point(module_scope)
